# Generated by Django 5.1.1 on 2024-09-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
